---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-password
spec:
  allowRepeat: true
  encoding: "base64"
  length: 60
  noUpper: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        AUTHENTIK_SECRET_KEY: "{{ .password }}"
        GRAFANA_CLIENT_ID: "{{ .grafana_oauth_client_id }}"
        GRAFANA_CLIENT_SECRET: "{{ .grafana_oauth_client_secret }}"
        HARBOR_CLIENT_ID: "{{ .harbor_oauth_client_id }}"
        HARBOR_CLIENT_SECRET: "{{ .harbor_oauth_client_secret }}"
        FOREJO_CLIENT_ID: "{{ .forejo_oauth_client_id }}"
        FOREJO_CLIENT_SECRET: "{{ .forejo_oauth_client_secret }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authentik-password
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: "(.*)"
            target: "grafana_$1"
    - extract:
        key: harbor
      rewrite:
        - regexp:
            source: "(.*)"
            target: "harbor_$1"
    - extract:
        key: forejo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "forejo_$1"
