---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/tcproute_v1alpha2.json
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: forejo-ssh
spec:
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: ssh
  rules:
    - backendRefs:
        - name: forejo-forgejo-ssh
          port: 22
