---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forejo-runner-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forejo-runner-token
    template:
      type: Opaque
      data:
        .runner: "{{ index . \".runner\" }}"
  dataFrom:
    - extract:
        key: forejo-runner-token
