---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backup-daily.yaml
  - ./snapshot-6h.yaml
  - ./snapshot-cleanup.yaml
  - ./trim-weekly.yaml
