apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: "0 3,9,15,21 * * *"
  groups:
    - default
  name: snapshot-cleanup
  retain: 0
  task: snapshot-cleanup
