---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
radarr:
  radarr:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer

    quality_definition:
      type: movie

    quality_profiles:
      - trash_id: 64fb5f9858489bdac2af690e27c8f42f # UHD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        name: UHD Bluray + WEB
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: Bluray-1080p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-720p

    custom_format_groups:
      add:
        # - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76 # [HDR Formats] DV (w/o HDR fallback)
        - trash_id: 1616617ab3a14397a2b2321bcbda44d1 # [HDR Formats] DV Boost
        - trash_id: b29413a7487478fe98228ce79e5689e4 # [HDR Formats] HDR10+ Boost
        - trash_id: 9337080378236ce4c0b183e35790d2a7 # [Optional] Miscellaneous
          select:
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
            - f700d29429c023a5734505e77daeaea7 # DV (Disk)
            - 73613461ac2cea99d52c4cd6e177ab82 # HFR
            - 4b900e171accbfb172729b63323ea8ca # Multi
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
            - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
            # - f537cf427b64c38c8e36298f657e4828 # Scene
            - 11cd1db7165d6a7ad9a83bc97b8b1060 # VC-1
            - ae4cfaa9283a4f2150ac3da08e388723 # VP9
            # - 2899d84dc9372de3408e6d8cc18e9666 # x264
            # - 9170d55c319f4fe40da8711ba9d8050d # x265
            # - 390455c22a9cac81a738f6cbad705c3c # x266
        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
        - trash_id: 47f0d69750de9e16855915fa73bb7b08 # [Optional] SDR
          select:
            - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        # - trash_id: 60f6d50cbd3cfc3e9a8c00e3a30c3114  # [Streaming Services] Anime
        # - trash_id: b22449f789b16a4163b59f1b70cbc580  # [Streaming Services] Asian
        # - trash_id: 088a792e0561c927fb396664b0db5c8f  # [Streaming Services] Dutch
        # - trash_id: 9fc645b3cef52b149ec13ba3972245d1  # [Streaming Services] Miscellaneous
        # - trash_id: f737e18b5824d6ebb2d57b957ae2fd6c  # [Streaming Services] UK

    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb

sonarr:
  sonarr:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true

    media_management:
      propers_and_repacks: do_not_prefer

    quality_definition:
      type: series

    quality_profiles:
      - trash_id: 9d142234e45d6143785ac55f5a9e8dc9 # WEB-1080p (Alternative)
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: e9a1944a254e6f8a9da63083f7ae15cb # [Audio] Audio Formats
        - trash_id: d920fd959d220306888f40b6f38e1578 # [Optional] Season Packs
        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
          select:
            - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
            - ef4963043b0987f8485bc9106f16db38 # DV (Disk)
            - 1bd69272e23c5e6c5b1d6c8a36fce95e # HFR
            - 7ba05c6e0e14e793538174c679126996 # MULTi
            - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
            - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
            - 06d66ab109d4d2eddb2794d21526d140 # Retags
            # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
            - 7470a681e6205243983c4410ee4c920f # VC-1
            - 90501962793d580d011511155c97e4e5 # VP9
            # - cddfb4e32db826151d97352b8e37c648 # x264
            # - c9eafd50846d299b862ca9bb6ea91950 # x265
            # - 041d90b435ebd773271cea047a457a6a # x266
        # - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a  # [Streaming Services] Asian
        # - trash_id: f60f4401ce880aad62e9d21c8bb6b91a  # [Streaming Services] Dutch
        # - trash_id: 848fd356c200568fc5a6248150e7e7ea  # [Streaming Services] French
        # - trash_id: 7832db22b71ab669458c17a2850d6913  # [Streaming Services] Miscellaneous
        # - trash_id: ddab3095a5d2f436f369263840af34f9  # [Streaming Services] UK

    media_naming:
      episodes:
        anime: default
        daily: default
        rename: true
        standard: default
      season: default
      series: plex-tvdb
